ARG NVIDIA_BASE_IMAGE=nvidia/cuda:12.6.3-base-ubuntu20.04
FROM $NVIDIA_BASE_IMAGE

RUN rm -rf /usr/local/cuda-*/compat/libcuda.so*
ENV NVIDIA_DISABLE_REQUIRE="true"
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility

ARG AUTHOR=mengkzhaoyun@gmail.com
ARG VERSION=v2.6.1-beagle
ARG TARGETOS=linux
ARG TARGETARCH=amd64
LABEL maintainer=${AUTHOR} version=${VERSION}

COPY ./LICENSE /k8s-vgpu/LICENSE
COPY ./bin/nvidia-device-plugin-${VERSION}-${TARGETOS}-${TARGETARCH} /k8s-vgpu/bin/nvidia-device-plugin
COPY ./bin/scheduler-${VERSION}-${TARGETOS}-${TARGETARCH} /k8s-vgpu/bin/scheduler
COPY ./bin/vGPUmonitor-${VERSION}-${TARGETOS}-${TARGETARCH} /k8s-vgpu/bin/vGPUmonitor
COPY ./bin/nvidia-mig-parted /k8s-vgpu/bin/nvidia-mig-parted
COPY ./docker/entrypoint.sh /k8s-vgpu/bin/entrypoint.sh
COPY ./docker/vgpu-init.sh /k8s-vgpu/bin/vgpu-init.sh

# 复制其他核心库和上一步流水线刚刚用 CMake/Nvcc 混合编译出来的核心劫持驱动
COPY ./lib /k8s-vgpu/lib
COPY ./bin/libvgpu.so /k8s-vgpu/lib/nvidia/libvgpu.so."$VERSION"

ENV PATH="/k8s-vgpu/bin:${PATH}"
ARG DEST_DIR
ENTRYPOINT ["/bin/bash", "-c", "entrypoint.sh  $DEST_DIR"]