ARG BASE

FROM ${BASE}

ARG AUTHOR=mengkzhaoyun@gmail.com
ARG VERSION=v2.6.1
ARG TARGETOS=linux
ARG TARGETARCH=amd64

LABEL maintainer=${AUTHOR} version=${VERSION}

ADD ./bin/nvidia-device-plugin-${VERSION}-${TARGETOS}-${TARGETARCH} /k8s-vgpu/bin/nvidia-device-plugin