ARG BASE=ubuntu:22.04
FROM $BASE

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y && apt-get install -y tzdata ca-certificates && rm -rf /var/lib/apt/lists/*

ARG AUTHOR=mengkzhaoyun@gmail.com
ARG VERSION=v2.6.1-beagle
ARG TARGETOS=linux
ARG TARGETARCH=arm64
LABEL maintainer=${AUTHOR} version=${VERSION}

COPY ./LICENSE /k8s-vgpu/LICENSE

# K8s Scheduler 主控与组件
COPY ./bin/nvidia-device-plugin-${VERSION}-${TARGETOS}-${TARGETARCH} /k8s-vgpu/bin/nvidia-device-plugin
COPY ./bin/scheduler-${VERSION}-${TARGETOS}-${TARGETARCH} /k8s-vgpu/bin/scheduler
COPY ./bin/vGPUmonitor-${VERSION}-${TARGETOS}-${TARGETARCH} /k8s-vgpu/bin/vGPUmonitor
COPY ./bin/nvidia-mig-parted /k8s-vgpu/bin/nvidia-mig-parted
COPY ./docker/entrypoint.sh /k8s-vgpu/bin/entrypoint.sh
COPY ./docker/vgpu-init.sh /k8s-vgpu/bin/vgpu-init.sh

# ARM64 信创环境（如包含华为华为算力的节点）不加载 nvidia 的底层 libvgpu.so 劫持库，因此无需拷贝编译出的 so
COPY ./lib /k8s-vgpu/lib

ENV PATH="/k8s-vgpu/bin:${PATH}"
ARG DEST_DIR
ENTRYPOINT ["/bin/bash", "-c", "entrypoint.sh  $DEST_DIR"]
