ARG BASE=projecthami/hami:v2.6.1

FROM ${BASE} AS hami

ARG AUTHOR=mengkzhaoyun@gmail.com
ARG VERSION=v2.6.1
ARG TARGETOS=linux
ARG TARGETARCH=amd64

LABEL maintainer=${AUTHOR} version=${VERSION}

ADD ./bin/nvidia-device-plugin-${VERSION}-${TARGETOS}-${TARGETARCH} /k8s-vgpu/bin/nvidia-device-plugin
ADD ./bin/scheduler-${VERSION}-${TARGETOS}-${TARGETARCH} /k8s-vgpu/bin/scheduler
COPY --from=hami  /k8s-vgpu/lib/nvidia/libvgpu.so.v2.6.1 /k8s-vgpu/lib/nvidia/libvgpu.so."$VERSION"