name: Build CANN Plugin Image

on:
  push:
    branches:
      - cann

env:
  BUILD_VERSION: v2.6.2
  CANN_PLUGIN_SOURCE_IMAGE: registry.cn-qingdao.aliyuncs.com/wod/ascend-device-plugin:v1.2.0-arm64

jobs:
  build-cann:
    name: Retag CANN Plugin Image
    runs-on: ubuntu-latest
    steps:
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      - name: Pull, tag and push CANN plugin image
        run: |
          docker pull --platform linux/arm64 ${{ env.CANN_PLUGIN_SOURCE_IMAGE }}
          docker tag ${{ env.CANN_PLUGIN_SOURCE_IMAGE }} ghcr.io/${{ github.repository_owner }}/hami:${{ env.BUILD_VERSION }}-cann
          docker tag ${{ env.CANN_PLUGIN_SOURCE_IMAGE }} registry.cn-qingdao.aliyuncs.com/wod/hami:${{ env.BUILD_VERSION }}-cann
          docker push ghcr.io/${{ github.repository_owner }}/hami:${{ env.BUILD_VERSION }}-cann
          docker push registry.cn-qingdao.aliyuncs.com/wod/hami:${{ env.BUILD_VERSION }}-cann
